# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# DescargaVUR.py
# Created on: 2019-10-16 09:36:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: DescargaVUR <lista_Descarga> <Agrupar> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

import os
import subprocess

dir_path = os.path.dirname(os.path.realpath(__file__))

print dir_path

# Script arguments
lista_Descarga = arcpy.GetParameterAsText(0)
if lista_Descarga == '#' or not lista_Descarga:
    lista_Descarga = dir_path+"\\..\\Tables\\descarga.xls\\Hoja1$" # provide a default value if unspecified

Agrupar = arcpy.GetParameterAsText(1)
if Agrupar == '#' or not Agrupar:
    Agrupar = "FMI #" # provide a default value if unspecified

fTable = lista_Descarga
field = Agrupar
print (lista_Descarga)
print (Agrupar)
pag = "https://www.vur.gov.co/portal/pages/vur/inicio.jsf"
print dir_path+"\\chrome-win\\chrome.exe "

subprocess.call(dir_path+"\\..\\chrome-win\\chrome.exe "+pag)



