# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# printVUR.py
# Created on: 2019-10-16 09:36:10.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: printVUR <carpeta Vur descargados>
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
#import arcpy

import os
import subprocess
from os import listdir
from os.path import isfile, join


dir_path = os.path.dirname(os.path.realpath(__file__))

#print dir_path

# Script arguments
#parte1 = arcpy.GetParameterAsText(0)
# if parte1 == '#' or not parte1:
#     parte1 = "C:\\CoPropiedad\\Downloads"
parte1 = "C:\\CoPropiedad\\Downloads"

pag = "https://www.vur.gov.co/portal/pages/vur/inicio.jsf"



#print dir_path+"\\chrome-win\\chrome.exe "



onlyfiles = [f for f in listdir(parte1) if isfile(join(parte1, f))]

datosB = []
estadoJ = []

for file in onlyfiles:
    if "FULLDATA" in file:
        continue
    lfile = os.path.splitext(file)[0]
    if ".html" in file and "DB" in file:
        #print "Procesando "+file
        archivo =  os.path.join(parte1, file)
        printLine = ' --headless --print-to-pdf="'+parte1+'\\'+lfile+'.pdf" --no-margins file:///'+archivo+' '
        subprocess.call(dir_path+"\\..\\chrome.exe "+printLine)
        
    if ".html" in file and "EJ" in file:
        archivo =  os.path.join(parte1, file)

        #print "Procesando "+file
        printLine = ' --headless --print-to-pdf="'+parte1+'\\'+lfile+'.pdf" --no-margins file:///'+archivo+' '
        subprocess.call(dir_path+"\\..\\chrome.exe "+printLine)
        


