# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# VURJsonToTable.py
# Created on: 2019-10-22 13:38:02.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: VURJsonToTable <parte1> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
import json
import csv
import re
from os import listdir
from os.path import isfile, join


# Script arguments
parte1 = arcpy.GetParameterAsText(0)
if parte1 == '#' or not parte1:
    parte1 = "C:\\CoPropiedad\\Downloads" # provide a default value if unspecified

onlyfiles = [f for f in listdir(parte1) if isfile(join(parte1, f))]


datosB = []
estadoJ = []

for file in onlyfiles:
    if ".json" in file and "DB" in file:
        archivo =  os.path.join(parte1, file)
        with open(archivo) as json_file:
            data = json.load(json_file)
            datosB.append(data)
    if ".json" in file and "EJ" in file:
        archivo =  os.path.join(parte1, file)
        with open(archivo) as json_file:
            data = json.load(json_file)
            estadoJ.append(data)

regex = re.compile(r'[\n\r\t]')

row = ['fecha', 'hora', 'Nro Consulta','fmi','referencia catastral','referencia catastral anterior' ,'cedula catastral','departamento','municipio','vereda','direccion','direcciones anteriores','fecha apertura folio','tipo instrumento','fecha instrumento','estado folio','matriculas matriz','matriculas derivadas','tipo de predio','alertas','propietarios','complementaciones','linderos','salvedades','propietartio ecopetrol?']
with open(os.path.join(parte1, "DBVUR.csv"), 'a') as csvFile:
    writer = csv.writer(csvFile, delimiter='|',  quoting=0)
    writer.writerow(row)

    for jsonObj in datosB:
        fila = []
        fecha = jsonObj['fecha']
        fila.append(fecha)
        hora = jsonObj['hora']
        fila.append(hora)
        nConsulta = jsonObj['numeroConsulta']
        fila.append(nConsulta)
        fmi = jsonObj['circulo']+"-"+jsonObj['numeroMatricula']
        fila.append(fmi)
        print "procesando "+fmi

        if 'referenciaCatastral' in jsonObj.keys():
            fila.append(jsonObj['referenciaCatastral'].encode('utf-8').strip())
        else:
            fila.append("0")
        
        
        if  'referenciaCatastralAnterior' in jsonObj.keys():
            fila.append(jsonObj['referenciaCatastralAnterior'].encode('utf-8').strip())
        else:
            fila.append("0")

        if  'cedulaCatastral' in jsonObj.keys():
            fila.append(jsonObj['cedulaCatastral'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'departamento' in jsonObj.keys():
            fila.append(jsonObj['departamento']['nombre'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'municipio' in jsonObj.keys():
            fila.append(jsonObj['municipio']['nombre'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'vereda' in jsonObj.keys():
            fila.append(jsonObj['vereda'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'direccion' in jsonObj.keys():
            fila.append(jsonObj['direccion'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'direccionesAnteriores' in jsonObj.keys():
            fila.append(str(jsonObj['direccionesAnteriores']).encode('utf-8').strip())
        else:
            fila.append("0")

        if 'fechaAperturaFolio' in jsonObj.keys():
            fila.append(jsonObj['fechaAperturaFolio'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'tipoInstrumento' in jsonObj.keys():
            fila.append(jsonObj['tipoInstrumento'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'fechaInstrumento' in jsonObj.keys():
            fila.append(jsonObj['fechaInstrumento'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'estadoFolio' in jsonObj.keys():
            fila.append(jsonObj['estadoFolio'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'matriculasMatriz' in jsonObj.keys():
            fila.append("; ".join(jsonObj['matriculasMatriz']))
        else:
            fila.append("0")

        if 'matriculasDerivadas' in jsonObj.keys():
            fila.append("; ".join(jsonObj['matriculasDerivadas']))
        else:
            fila.append("0")

        if 'tipoPredio' in jsonObj.keys():
            fila.append(jsonObj['tipoPredio'].encode('utf-8').strip())
        else:
            fila.append("0")

        if 'medidasCautelares' in jsonObj.keys():
            fila.append(("; ".join(jsonObj['medidasCautelares']).encode('utf-8').strip()).rstrip(os.linesep))
        else:
            fila.append("0")

        if 'propietarios' in jsonObj.keys():
            strProp = ""
            for prop in jsonObj['propietarios']:
                strProp +="Doc Nro: "+prop['numeroDocumento']+ " - "
                nombre = prop['nombre'].replace(u'\xd1', 'n')
                nombre = nombre.replace(u'\xf1', 'N')
                strProp +="Nombre: "+nombre
                strProp +="    ;"
            fila.append(strProp)
                            
        else:
            fila.append("0")

        if 'complementaciones' in jsonObj.keys():
            complementaciones =(jsonObj['complementaciones'].encode('utf-8').strip()).rstrip(os.linesep)
            complementaciones = regex.sub(" ", complementaciones)
            fila.append(complementaciones)
        else:
            fila.append("0")

        if 'linderos' in jsonObj.keys():
            linderos = (jsonObj['linderos'].encode('utf-8').strip()).rstrip(os.linesep)
            linderos = regex.sub(" ", linderos)
            fila.append(linderos)
        else:
            fila.append("0")

        if 'salvedades' in jsonObj.keys():
            cadSal = ""
            for sal in jsonObj['salvedades']:
                cadSal += "Nro. Anotacion: "+sal['numeroAnotacion'].encode('utf-8').strip()+ " - "
                cadSal += "Nro. Correccion: "+sal['numeroCorreccion'].encode('utf-8').strip()+ " - "
                radSal = "";
                if "radicacionSalvedad" in sal:
                    radSal = sal['radicacionSalvedad'].encode('utf-8').strip()
                
                cadSal += "Radicación Salvedad: "+radSal+ " - "
                
                descrip = "Descripcion: "+(sal['descripcion'].encode('utf-8').strip()).rstrip(os.linesep)
                descrip = regex.sub(" ", descrip)
                cadSal += descrip
                cadSal += "    ;"
            fila.append(cadSal)
        else:
            fila.append("0")

        if "ECOPETROL".lower() in strProp.lower() or "EMPRESA COLOMBIANA DE PETROLEOS".lower() in strProp.lower() or "ECP".lower() in strProp.lower():
            fila.append("SI")
        else:
            fila.append("NO")
            

        print fila
        writer.writerow(fila)
        print "Fila agregada FMI "+fmi
csvFile.close()
print "Cierra Fichero DB"
row2 = ['fecha', 'hora', 'Nro Consulta','fmi','Nro Anotacion','Anotacion','Mutacion','Servidumbre de hidrocarburos?', 'servidumbre?']
with open(os.path.join(parte1, "EJVUR.csv"), 'a') as csvFile2:
    writer2 = csv.writer(csvFile2, delimiter='|',  quoting=0)
    writer2.writerow(row2)
    
    for ej in estadoJ:
        cont = 0
        if 'textoAnotaciones' in ej.keys():
            for txt in ej['textoAnotaciones']:
                cont = cont+1
                fila2 = []
                fecha2 = ej['fecha']
                fila2.append(fecha2)
                hora2 = ej['hora']
                fila2.append(hora2)
                nConsulta2 = ej['consulta']
                fila2.append(nConsulta2)
                fmi2 = ej['circulo']+"-"+ej['numeroMatricula']
                fila2.append(fmi2)
                fila2.append(cont)
                print "procesando EJ "+fmi2
                anot = regex.sub(" ", (txt.encode('utf-8').strip()).rstrip(os.linesep))
                fila2.append(anot)
                print fila2
                if cont ==1:
                    if "DESENGLOBE".lower() in anot.lower():
                        fila2.append("'01")
                    elif "ENGLOBE".lower() in anot.lower():
                        fila2.append("'02")
                    elif "FALSA TRADICION".lower() in anot.lower():
                        fila2.append("'04")
                    else:
                        fila2.append("'06")
                else:
                    fila2.append("'00")
                if "HIDROCARBUROS".lower() in anot.lower() or "PETROLEOS".lower() in anot.lower() or "PETROLER".lower() in anot.lower() or "OLEODUCTO".lower() in anot.lower() or "GASODUCTO".lower() in anot.lower():
                    fila2.append("SI")
                else:
                    fila2.append("NO")
                if "SERVIDUMBRE".lower() in anot.lower() :
                    fila2.append("SI")
                else:
                    fila2.append("NO")
                    
                writer2.writerow(fila2)
                print "Fila agregada FMI "+fmi2
        
csvFile2.close()
print "Cierra Fichero EJ"


